apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chickadee-nodejs 
  janus-idp.io/tekton: chickadee-nodejs
  backstage.io/kubernetes-id: chickadee-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chickadee-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  